### ISSUE TITLE
next 12 support?

### ISSUE THREAD

**Issue by bonesoul** [iamvishnusankar/next-sitemap#227]
updated my project to next 12 and trying to use next-sitemap getting:

```
Loaded env from D:\Coding\vizesizgezi\frontend\.env.production
Loaded env from D:\Coding\vizesizgezi\frontend\.env
D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:31
        ...Object.keys(manifest.build.pages),
                                      ^

TypeError: Cannot read properties of undefined (reading 'pages')
    at D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:31:39
    at Generator.next (<anonymous>)
    at D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:4:12)
    at Object.exports.createUrlSet (D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:28:46)
    at D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\cli.js:34:32
    at Generator.next (<anonymous>)
    at D:\Coding\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\cli.js:8:71
    at new Promise (<anonymous>)
```

**Comment by flowck** [comment]
I am facing the same issue.

**Comment by benwinding** [comment]
Getting the same issue in next version 10 
😟

**Comment by benwinding** [comment]
I don't think this is related to `next@12`

You might just need to add `sourceDir` to the configuration file. In my case I changed the output to `dist`
```
// next-sitemap.js
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://example.com',
  generateRobotsTxt: true, // (optional)
  sourceDir: 'dist', 
  // ^ ADD THIS HERE
}
```
Related to #117 and #91

**Comment by bonesoul** [comment]
well when i remove my next.js distDir customization, it just works.

but as your suggestion; 

```
  distDir: 'build', // use build dir.
  sourceDir: 'build'

```

using a custom distDir instead of .next and setting sourceDir for next-sitemap still doesn't work;


```
> vizesizgezi@0.1.0 postbuild
> cross-env next-sitemap --config sitemap.config.js

Loaded env from E:\source\vizesizgezi\frontend\.env.production
Loaded env from E:\source\vizesizgezi\frontend\.env
E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:31
        ...Object.keys(manifest.build.pages),
                                      ^

TypeError: Cannot read properties of undefined (reading 'pages')
    at E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:31:39
    at Generator.next (<anonymous>)
    at E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:4:12)
    at Object.exports.createUrlSet (E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\url\create-url-set\index.js:28:46)
    at E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\cli.js:34:32
    at Generator.next (<anonymous>)
    at E:\source\vizesizgezi\frontend\node_modules\next-sitemap\dist\cjs\cli.js:8:71
    at new Promise (<anonymous>)
```
