### ISSUE TITLE
Error: Cannot find module 'node:fs/promises'

### ISSUE THREAD

**Issue by owex** [iamvishnusankar/next-sitemap#307]
When attempting to run next-sitemap, i encounter this error, any help is much appreciated. 

**How to Recreate:** 
Execute the sitemap command. 
`next-sitemap`

**Error Message**
```
> tabcreator@0.1.0 postbuild /Users/tony.stark/Personal/projectx
> next-sitemap

Loaded env from /Users/tony.stark/Personal/projectx/.env.local
Loaded env from /Users/tony.stark/Personal/projectx/.env
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:fs/promises'
Require stack:
- /Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/file/index.js
- /Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/config/index.js
- /Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/cli.js
- /Users/tony.stark/Personal/projectx/node_modules/next-sitemap/bin/next-sitemap
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/file/index.js:17:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/file/index.js',
    '/Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/config/index.js',
    '/Users/tony.stark/Personal/projectx/node_modules/next-sitemap/dist/cjs/cli.js',
    '/Users/tony.stark/Personal/projectx/node_modules/next-sitemap/bin/next-sitemap'
  ]
}
````

**Comment by iamvishnusankar** [comment]
@owex Duplicate #281

**Comment by owex** [comment]
> @owex Duplicate #281

Thank you!

**Comment by ferremek** [comment]
Hey guys,

I still seem to have this issue. I even downloaded the [/examples/basic](https://github.com/iamvishnusankar/next-sitemap/tree/master/examples/basic) folder and run into the same issue. I have npm version `v15.3.0` and node version `7.0.14`.

I followed the docs instructions and created a `./next-sitemap.js` in the root folder with the following:
```
module.exports = {
  siteUrl: process.env.SITE_URL,
  generateRobotsTxt: true,
};
```

Any ideas on how I can fix this?

Thanks!

<img width="840" alt="Schermafbeelding 2022-05-16 om 14 02 16" src="https://user-images.githubusercontent.com/15103617/168588344-49376dd5-cdf3-463d-bca9-f82cda7d2b48.png">
