### ISSUE TITLE
yarn build give error "Potentially dangerous"

### ISSUE THREAD

**Issue by FireIndex** [iamvishnusankar/next-sitemap#371]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js build

PATH: 
  C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Users\satya\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\satya\AppData\Local\Programs\Python\Python310\;C:\Users\satya\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Program Files\heroku\bin;C:\Users\satya\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\satya\AppData\Roaming\npm

Yarn version: 
  1.22.18

Node version: 
  16.13.1

Platform: 
  win32 x64

Trace: 
  Error: **Potentially dangerous call to "next-sitemap" in D:\CODE BIN\NEW IDEA\mkvwatch.xyz**
      at validate (C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25658:15)
      at C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25726:7
      at new Promise (<anonymous>)
      at new F (C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:5301:28)
      at C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25725:12
      at run (C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:43176:7)
      at BlockingQueue.maybePushConcurrencyQueue (C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:43191:7)
      at BlockingQueue.shift (C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:43186:10)
      at C:\Users\satya\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:43130:15
      at new Promise (<anonymous>)
.......Carry on error......👇

**Screenshots**

**Additional context**

**Comment by adnan007d** [comment]
Same Error 😞

**Comment by necheporenko** [comment]
Me too
https://github.com/iamvishnusankar/next-sitemap/issues/389#issuecomment-1143454017
