### ISSUE TITLE
Error: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by sahit402702** [iamvishnusankar/next-sitemap#584]
I am trying to integrate this in my next js application. 
**Dependencies version:
"next-sitemap": "^3.1.52",
 "node": "^16.13.2",
"next": 10.x**

When I'm trying to run the build getting this error:

> Build error occurred        
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\402702\Latest\app-web-refresh\node_modules\next-sitemap\dist\cjs\index.js
require() of ES modules is not supported.
require() of repo\node_modules\next-sitemap\dist\cjs\index.js from repo\.next\server\pages\server-sitemap-index.xml.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from repo\node_modules\next-sitemap\package.json.

    at new NodeError (node:internal/errors:278:15)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.5Voz (repo\.next\server\pages\server-sitemap-index.xml.js:107:18)
    at __webpack_require__ (repo\.next\server\pages\server-sitemap-index.xml.js:23:31)     
    at Module.hl4A (repo\.next\server\pages\server-sitemap-index.xml.js:118:70)
    at __webpack_require__ (repo\.next\server\pages\server-sitemap-index.xml.js:23:31) {   
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by iamvishnusankar** [comment]
@sahit402702 Duplicate #404
